### ISSUE TITLE
URL.host is added as path component and prevents route matching

### ISSUE THREAD

**Issue by radianttap** [joeldev/JLRoutes#67] opened 2016-04-15 14:22 UTC
I have this route setup:
```
[JLRoutes addRoute:@"/playeractivation" handler:^BOOL(NSDictionary *parameters) {...}
```

The incoming URL (universal links) is this: `https://websitename.rs/playeractivation?player=aleck@site.rs&code=123142`

Everything goes until line 518 in JLRoutes.m :

```
	if (URL.host.length > 0 && ![URL.host isEqualToString:@"localhost"]) {
		// For backward compatibility, handle scheme://path/to/ressource as if path was part of the
		// path if it doesn't look like a domain name (no dot in it)
		pathComponents = [@[URL.host] arrayByAddingObjectsFromArray:pathComponents];
	}
```
This piece of code picks up the `websitename.rs` and adds it to the existing `playeractivation` (which is the only path component).
Thus, when it later gets in line 173, to this:

```
    BOOL componentCountEqual = patternComponents.count == components.count;
    BOOL patternContainsWildcard = [patternComponents containsObject:@"*"];
    if (componentCountEqual || patternContainsWildcard) {
```

That first boolean is NO, because components has two elements and patternComponents has only one (which is correct).

**What's the purpose of that block above?**

The comment says:
```
		// For backward compatibility, handle scheme://path/to/ressource as if path was part of the
		// path if it doesn't look like a domain name (no dot in it)
```
but it never actually checks for the existence of the `.` in the URL.host, it just blindly adds it.

**Comment by abbasmousavi** [comment] 2016-06-20 08:30
This commit, breaks route matching on iOS 9. @radianttap.
I have comment it out in my code and route matching is working again.

**Comment by zats** [comment] 2016-07-06 21:37
We ran into the same issue, our scenario is that we are using router both for external universal links (`https://myapp.com/path`) and for internal links (`myapp://path`), also we need to support several environments, so in our case universal links can be `https://dev.myapp.com/path` or `https://staging.myapp.com/path` or `https://myapp.com/path`
I'm not sure I understand the reasoning behind this change, not sure if I've seen other routing solutions to match against the host (similar ruby libraries for example)

**Comment by ekampf** [comment] 2016-07-06 21:38
Traced back to this commit: https://github.com/joeldev/JLRoutes/commit/98febf4d03b0610961f24bf0d42010c1c8be4b56#diff-49786c8b72bf93a052e6bbaf95b8b295R444

Seems more like a regression than an improvement...

@joeldev is the intended behaviour that route has to contain the host?  seems odd...

**Comment by joeldev** [comment] 2016-07-07 05:28
Sorry for the trouble, everyone. I just reverted the changes made in this commit (e9536fdbbc0f65151110768501d40746e42bceba).

**Comment by joeldev** [comment] 2016-07-07 05:30
I'm going to close this issue for now. Please feel free to re-open (or file another issue) if me reverting that commit has caused some other issue. All current tests are passing and I'm always looking to add more.

**Closed by joeldev** 2016-07-07 05:30 UTC

**Comment by zats** [comment] 2016-07-07 12:52
Thank you

**Comment by mjarvis** [comment] 2017-01-11 23:47
@joeldev This issue appears to be reoccurring. `JLRRouteRequest.m:L33-38` adds the host as a path component. Is this an intentional change for 2.0? It does not match the routing behaviour from the 1.x versions of JLRoutes.

Here is a failing test that indicates this problem:

```objective-c
- (void)testHostIgnored
{
    [[JLRoutes globalRoutes] addRoute:@"/someRoute/123"
                              handler:[[self class] defaultRouteHandler]];

    [self route:@"https://google.com/someRoute/123"];
    JLValidateAnyRouteMatched();
}
```

If this is intentional, it would be a good idea to document the change in behaviour in the 2.0.0 release notes and possibly a "migrating to 2.x" document, as people will need to add manual stripping of the host to bring back the old behaviour.
